apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-digvijay
    image: nginx
    ports: 
    - containerPort: 8080
  - name: watcher-digvijay
    image: afakharany/watcher
    
